# Application Name

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    secure-port-enabled: true
    non-secure-port-enabled: false

# MySQL Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wishwhiz?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123qwerty
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

# Server SSL Configuration
server:
  ssl:
    key-store: classpath:eureka-client.p12
    key-store-password: Chemn1tz
    key-alias: eureka-client
    key-store-type: PKCS12
