server:
  port: 8081

spring:
  application:
    name: order-service
  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mysql://localhost:3306/WishWhiz
    username: root
    password: 123qwerty
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 60000 # 60 seconds idle timeout
      connection-timeout: 30000 # 30 seconds to wait for a connection
      max-lifetime: 1800000 # 30 minutes for maximum connection lifetime

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  cache:
    type: caffeine

  cloud:
    loadbalancer:
      cache:
        enabled: true
        ttl: 60s # Cache instances for 60 seconds

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/ # Basic Auth in URL
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 15
    instance-info-replication-interval-seconds: 10
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 8
    eureka-server-total-retries: 8
    eureka-server-retry-interval-seconds: 5
    service-url-poll-interval-seconds: 10
    enabled: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    hostname: ${spring.application.name}-${random.uuid}
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      zone: primary
      cluster: main
    status-page-url: http://localhost:${server.port}/actuator/info # Correct Actuator URL
    health-check-url: http://localhost:${server.port}/actuator/health # Ensure Eureka can reach healthcheck endpoint

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    cache:
      enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        retryer: feign.Retryer.Default
        errorDecoder: feign.codec.ErrorDecoder.Default
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  basic-auth:
    admin:
      username: admin
      password: admin123

logging:
  level:
    com.netflix.eureka: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.boot.actuate.endpoint: DEBUG
