spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/WishWhiz
    username: root
    password: 123qwerty
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
