server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:eureka-server.p12
    key-store-password: Chemn1tz
    key-password: Chemn1tz
    key-alias: eureka-server
    key-store-type: PKCS12

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
    non-secure-port-enabled: false
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

spring:
  application:
    name: eurekaserver
